[versions]
kotlin = "2.0.0"
spring = "3.3.4"
spring-web = "6.1.13"
spring-dep-management = "1.1.5"
tomcat = "10.1.25"

h2 = "2.2.224"
postgres = "42.7.3"
hibernate = "6.5.2.Final"

fasterxml-jackson = "2.17.1"
junit-launcher = "1.10.2"
jakarta = "3.1.0"
yaml = "2.2"
hikaricp = "5.1.0"

[libraries]
springboot-tomcat = { module = "org.springframework.boot:spring-boot-starter-tomcat", version.ref = "spring" }
springboot-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "spring" }
springboot-logging = { module = "org.springframework.boot:spring-boot-starter-logging", version.ref = "spring" }
spring-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "spring" }
spring-datajpa = { module = "org.springframework.data:spring-data-jpa", version.ref = "spring" }
spring-web = { module = "org.springframework:spring-web", version.ref = "spring-web" } # ?
spring-webmvc = { module = "org.springframework:spring-webmvc", version.ref = "spring-web" }
spring-websocket = { module = "org.springframework:spring-websocket", version.ref = "spring-web" }
spring-messaging = { module = "org.springframework:spring-messaging", version.ref = "spring-web" }

fasterxml-jackson = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "fasterxml-jackson" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
h2-database = { module = "com.h2database:h2", version.ref = "h2" }
junit-plateform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-launcher" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgres" }
jakarta-persistence = { module = "jakarta.persistence:jakarta.persistence-api", version.ref = "jakarta" }
hibernate-core = { module = "org.hibernate.orm:hibernate-core", version.ref = "hibernate" }
yaml-snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "yaml" }
zaxxer-hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }

[plugins]
springboot-framework = { id = "org.springframework.boot", version.ref = "spring" }
springboot-dep-management = { id = "io.spring.dependency-management", version.ref = "spring-dep-management" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
